projecteval/api/controllers/game.py
from flask import Blueprint, session, request, jsonify, abort

from projecteval import db

from projecteval.api.models.db import Game, Gameplatform

from projecteval.api.models.forms import EditGameForm

gameapi = Blueprint('gameapi', __name__)


@gameapi.route('/api/games/', methods=['GET'], strict_slashes = False)
def all_games():
	fields = request.args.get('fields')
	games = Game.query.all()

	json_result = []

	for game in games:
		json_result.append(game.toJSON(fields))

	return jsonify(games=json_result)

@gameapi.route('/api/games/<int:id>/', methods=['GET'], strict_slashes = False)
def game_info(id):
	game = Game.query.filter_by(id=id).first()

	if(game == None):
		abort(404)
		
	return jsonify(game=game.toJSON())

@gameapi.route('/api/edit/game/', methods=['POST'], strict_slashes = False)
def edit_game(platformIds):
	errors = [];
	id = request.form.get('id')
	releaseDate = request.form.get('release_date')
	developer = request.form.get('developer')
	publisher = request.form.get('publisher')
	description = request.form.get('desc')
	trailerUrl = request.form.get('trailer')
	title = request.form.get('title')
	platforms = set([int(x) for x in platformIds])

	form = EditGameForm(id=id, description=description, releaseDate=releaseDate, developer=developer, publisher=publisher, trailerUrl=trailerUrl, title=title)
	# EditGameForm doesn't take trailerUrl and description values initially, use below as a workaround	
	form.description.data = description
	form.trailerUrl.data = trailerUrl

	# Validate platforms outside of Form as workaround for now
	if not validatePlatformIds(platforms):
		errors.append('Game requires at least one platform')

	if form.validate() and not errors:
		dbsession = db.session()
		game = Game.query.filter_by(id=id).first()
		if (game != None):
			# Update game here
			game.title = title
			game.release_date = releaseDate
			game.desc = description
			game.developer = developer
			game.publisher = publisher
			game.trailer_url = trailerUrl

			gameplatforms = Gameplatform.query.filter_by(game_id=game.id).all()
			currentIds = set()

			for g in gameplatforms:
				currentIds.add(g.platform_id)

			if not currentIds.issubset(platforms):
				for cId in currentIds:
					if not cId in platforms:
						deleteThis = Gameplatform.query.filter_by(game_id=game.id, platform_id=cId).first()
						dbsession.delete(deleteThis)
					else:
						platforms.remove(cId)

			if len(platforms) > 0:
				for addId in platforms:
					exists = Gameplatform.query.filter_by(game_id=game.id, platform_id=addId).first()

					if not exists:
						addThis = Gameplatform(game.id, addId)
						dbsession.add(addThis)

			# To Do: add functionality for ESRB and platforms
			dbsession.commit()
			return jsonify({"success":"true"})
		else:
			errors.append("No such game exists!")		
	else:
		errors_to_json(form, errors)

	return jsonify({"success":"false", "errors":errors})

def validatePlatformIds(platforms):
	if len(platforms) <= 0:
		return False

	return True
	
def errors_to_json(form, errors_arr):
	for field, errors in form.errors.items():
		for error in errors:
			errors_arr.append(error)

projecteval/controllers/games.py
from flask import Blueprint, request, render_template, session, url_for, redirect
import json
import projecteval.api.controllers.game as gameapi
import projecteval.api.controllers.platform as platformapi
import projecteval.controllers.helpers as helper

games = Blueprint('games', __name__)


@games.route('/games/', methods=['GET'])
def all_games():
    response = gameapi.all_games()
    helper.check_response(response)
    games = json.loads(response.data)
    games = games["games"]
    return render_template("games/games.html", games=games)

@games.route('/games/<int:id>', methods=['GET'])
def game_info(id=None):
    if (id is None):
        return self.all_games()
    response = gameapi.game_info(id)
    helper.check_response(response)
    game = json.loads(response.data)
    game = game["game"]
    game["release_date"] = helper.convert_date_string(game["release_date"])
    return render_template("games/game.html", game=game)

@games.route('/edit/games/<int:id>', methods=['GET'])
def edit_game(id=None):
    if (id is None):
        return redirect(url_for('games.all_games'), 302)
    if (not session["user_id"]):
        return redirect(url_for('games.game_info', id=id), 302)
    response = gameapi.game_info(id)
    platform_response = platformapi.all_platforms()

    helper.check_response(response)
    helper.check_response(platform_response)

    platform_list = json.loads(platform_response.data)
    platform_list = platform_list["platforms"]

    game = json.loads(response.data)
    game = game["game"]   
    game["release_date"] = helper.convert_date_string(game["release_date"])
    
    return render_template("edit/edit_game.html", game=game, platform_list=platform_list)

@games.route('/edit/games/', methods=['POST'])
def save_game():
    if (not session["user_id"]):
        return redirect(url_for('games.all_games'), 302)

    platformIds = helper.extractPlatformIds(request.form)

    return gameapi.edit_game(platformIds)

projecteval/games/controllers.py
from flask import Blueprint, request, jsonify, render_template, flash, session, url_for, redirect

import json

from projecteval import db

from projecteval.api.models import Game, Platform

import projecteval.api.controllers as api

import projecteval.helper.controllers as helper

games = Blueprint('games', __name__)


# Game
@games.route('/games/', methods=['GET'])
def all_games():
    response = api.all_games()
    helper.check_response(response)
    games = json.loads(response.data)
    games = games["games"]
    return render_template("games/games.html", games=games)

@games.route('/games/<int:id>', methods=['GET'])
def game_info(id=None):
    if (id is None):
        return self.all_games()
    response = api.game_info(id)
    helper.check_response(response)
    game = json.loads(response.data)
    game = game["game"]
    game["release_date"] = helper.convert_date_string(game["release_date"])
    return render_template("games/game.html", game=game)

@games.route('/edit/games/<int:id>', methods=['GET'])
def edit_game(id=None):
    if (id is None):
        return redirect(url_for('games.all_games'), 302)
    if (not session["user_id"]):
        return redirect(url_for('games.game_info', id=id), 302)
    response = api.game_info(id)
    platform_response = api.all_platforms()

    helper.check_response(response)
    helper.check_response(platform_response)

    platform_list = json.loads(platform_response.data)
    platform_list = platform_list["platforms"]

    game = json.loads(response.data)
    game = game["game"]   
    game["release_date"] = helper.convert_date_string(game["release_date"])
    
    return render_template("edit/edit_game.html", game=game, platform_list=platform_list)

@games.route('/edit/games/', methods=['POST'])
def save_game():
    if (not session["user_id"]):
        return redirect(url_for('games.all_games'), 302)

    platformIds = helper.extractPlatformIds(request.form)

    return api.edit_game(platformIds)

projecteval/templates/games/game.html
{% extends "layout/base.html" %}

{% block javascript %}{% endblock %}
{% block title %}{{ game['title'] }}{% endblock %}
{% block content %}
<h1>{{ game['title'] }}</h1>
    <div class="container">
       <!--Right column-->
        <div class="right-column">
            <!--Platform List-->
            <ul class="no-bullet display-inline">
                {{ macro.generate_labeled_platform_list(game, 'small-img') }}
            </ul>
            <ul class="no-bullet">
                <li>{{ macro.label_img('ESRB:', game['esrb_url']) }}</li>
                <li>{{ macro.label_data('Release Date:', game['release_date']) }}</li>
                <li>{{ macro.label_data('Developer:', game['developer']) }}</li>
                <li>{{ macro.label_data('Publisher:', game['publisher']) }}</li>
                <li>{{ macro.label_data('Average Rating:', '8', macro.rating_color(8)) }}</li>
            </ul>
        </div>
        <!--Left column-->
        <div class="left-column">
            <div class="section-block">
                <h2>Game Information</h2>
                {{ macro.text_block(game['desc']) }}
                <div><span class="label">Trailer:</span> <span class="data"><a href="{{ game['trailer_url'] }}">{{ game['trailer_url'] }}</a></span></div>
                {% if session['user_id'] and session['user_name'] %}
                    <div class="small-top-margin"><a href="{{ url_for('games.edit_game', id=game['id']) }}"><button>Edit Game</button></a></div>
                {% endif %}
            </div>
            <div class="section-block no-background">
                <h2>Tips</h2>
                <ul class="no-indent">
                    <li>Be awesome</li>
                    <li>Play awesome</li>
                    <li>Kill more than you die</li>
                </ul>
            </div>
            <div class="section-block">
                <h2>Reviews</h2>
                <ul class="no-bullet review">
                    <li>{{ macro.review("CrazyEarl", 9, "Where are you Scrappy? SCRRRRAAPPPPYYY!") }}</li>
                    <li>{{ macro.review("BoomBewm", 7, "Light the fuses bitches!") }}</li>
                    <li>{{ macro.review("Cl4P-TP", 2, "Jack thought he could stop us with a door? HA! I was MADE to open doors!...STAIRS? NOOOOOOOOOOOOOOOOOOOOOO! Minon, you've got to go on without me! Do your master proud!") }}</li>
                    <li>{{ macro.review("Scooter", 4, "Daisy, I like you a whole lot / More than that bandit liked spoonin' that ro-bot. / You are like a diamond in the rough / Or a flower surrounded by shrapnel and stuff. / I will hang myself from my own tombstone / if in you, I can't put my bone.") }}</li>
                </ul>
            </div>
        </div>
        <div class="clear-both">
        </div>
    </div>

<div>
    <a href="" onclick="window.history.go(-1); return false;">Go Back</a>
</div>
{% endblock %}

projecteval/templates/games/games.html
{% extends "layout/base.html" %}
{% block javascript %}{% endblock %}
{% block title %}Games{% endblock %}
{% block content %}
<h1>Games</h1>
<ul class="no-bullet">
    {% for game in games %}
    <li class="bottom-margin"><a href="{{ url_for('games.game_info', id=game['id']) }}" class="no-underline">{{ game["title"] }}</a>
        <ul class="no-bullet display-inline">
            {{ macro.generate_platform_list(game, 'small-img') }}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}