projecteval/api/controllers/platform.py
from flask import Blueprint, jsonify, abort, request

from projecteval.api.models.db import Platform

platformapi = Blueprint('platformapi', __name__)

@platformapi.route('/api/platforms/', methods=['GET'], strict_slashes = False)
def all_platforms():
	fields = request.args.get('fields')
	platforms = Platform.query.all()

	json_result = []

	for platform in platforms:
		json_result.append(platform.toJSON(fields))

	return jsonify(platforms=json_result)

@platformapi.route('/api/platforms/<int:id>/', methods=['GET'], strict_slashes = False)
def platform_info(id):
	platform = Platform.query.filter_by(id=id).first()

	if(platform == None):
		abort(404)

	return jsonify(platform=platform.toJSON())

projecteval/controllers/platforms.py
from flask import Blueprint, render_template
import json
import projecteval.api.controllers.platform as platformapi
import projecteval.controllers.helpers as helper

platforms = Blueprint('platforms', __name__)


@platforms.route('/platforms/', methods=['GET'])
def all_platforms():
    response = platformapi.all_platforms()
    helper.check_response(response)
    platforms = json.loads(response.data)
    platforms = platforms["platforms"]
    return render_template("platforms/platforms.html", platforms=platforms)

@platforms.route('/platforms/<int:id>', methods=['GET'])
def platform_info(id=None):
    if (id is None):
        return self.all_games()
    response = platformapi.platform_info(id)
    helper.check_response(response)
    platform = json.loads(response.data)
    platform = platform["platform"]
    platform["release_date"] = helper.convert_date_string(platform["release_date"])
    return render_template("platforms/platform.html", platform=platform)

projecteval/platforms/controllers.py
from flask import Blueprint, request, jsonify, render_template, flash

import json

from projecteval import db

from projecteval.api.models import Game, Platform

import projecteval.api.controllers as api

import projecteval.helper.controllers as helper

platforms = Blueprint('platforms', __name__)


# Platform
@platforms.route('/platforms/', methods=['GET'])
def all_platforms():
    response = api.all_platforms()
    helper.check_response(response)
    platforms = json.loads(response.data)
    platforms = platforms["platforms"]
    return render_template("platforms/platforms.html", platforms=platforms)

@platforms.route('/platforms/<int:id>', methods=['GET'])
def platform_info(id=None):
    if (id is None):
        return self.all_games()
    response = api.platform_info(id)
    helper.check_response(response)
    platform = json.loads(response.data)
    platform = platform["platform"]
    platform["release_date"] = helper.convert_date_string(platform["release_date"])
    return render_template("platforms/platform.html", platform=platform)

projecteval/templates/platforms/platform.html
{% extends "layout/base.html" %}
{% block javascript %}{% endblock %}
{% block title %}{{ platform['name'] }}{% endblock %}
{% block content %}
<h1>{{ platform['name'] }}</h1>
    <div class="container">
       <!--Right column-->
        <div class="right-column">
            
            <ul class="no-bullet">
                <li>{{ macro.platform_list(platform['name'], 'medium-img') }}</li>
                <li>{{ macro.label_data('Release Date:', platform['release_date']) }}</li>
                <li>{{ macro.label_data('Developer:', platform['developer']) }}</li>
                <li>{{ macro.label_data('CPU:', platform['cpu']) }}</li>
                <li>{{ macro.label_data('Memory:', platform['memory']) }}</li>
                <li>{{ macro.label_data('Graphics:', platform['graphics']) }}</li>
                <li>{{ macro.label_data('Storage:', platform['storage']) }}</li>
            </ul>
        </div>
        <!--Left column-->
        <div class="left-column">
            <div class="section-block">
                {{ macro.text_block(platform['desc']) }}
            </div>
        </div>
        <div class="clear-both">
        </div>
    </div>
<div>
    <a href="" onclick="window.history.go(-1); return false;">Go Back</a>
</div>
{% endblock %}

projecteval/templates/platforms/platforms.html
{% extends "layout/base.html" %}
{% block javascript %}{% endblock %}
{% block title %}Platforms{% endblock %}
{% block content %}
<h1>Platforms</h1>
<ul class="no-bullet display-inline">
    {% for platform in platforms %}
    <li class="li-right-margin">
        <a href="{{ url_for('platforms.platform_info', id=platform['id']) }}" title="{{platform['name']}}" class="no-underline">
            {{ macro.platform_list(platform['name'], 'medium-img') }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}